linters:
  enable:
    - errname
    - gocheckcompilerdirectives
    - gocyclo
    - lll
    - makezero
    - godot

linters-settings:
  gocyclo:
    min-complexity: 15
  lll:
    tab-width: 8
    line-length: 99
